name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Unit Tests
      run: go test -v ./...

    - name: Build main
      run: go build run-hw
  
    - name: Run main
      run: ./run-hw

    - name: Test main
      run: ./test-main.sh

